export CUDA_VISIBLE_DEVICES=1

model_name=iTransformer_multihead

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_96 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 256 \
  --d_ff 256 \
  --num_token_heads 4 \
  --use_dynamic_mask 1 \
  --token_mask_hidden 64 \
  --token_temperature 1.0 \
  --gate_temperature 1.0 \
  --fusion_type dynamic \
  --share_prediction_head 0 \
  --lambda_branch 0.2 \
  --lambda_redundancy 0.001 \
  --lambda_contribution 0.05 \
  --lambda_balance 0.01 \
  --contribution_margin 0.0001 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_192 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 256 \
  --d_ff 256 \
  --num_token_heads 4 \
  --use_dynamic_mask 1 \
  --token_mask_hidden 64 \
  --token_temperature 1.0 \
  --gate_temperature 1.0 \
  --fusion_type dynamic \
  --share_prediction_head 0 \
  --lambda_branch 0.2 \
  --lambda_redundancy 0.001 \
  --lambda_contribution 0.05 \
  --lambda_balance 0.01 \
  --contribution_margin 0.0001 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_336 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --e_layers 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 512 \
  --d_ff 512 \
  --num_token_heads 4 \
  --use_dynamic_mask 1 \
  --token_mask_hidden 64 \
  --token_temperature 1.0 \
  --gate_temperature 1.0 \
  --fusion_type dynamic \
  --share_prediction_head 0 \
  --lambda_branch 0.2 \
  --lambda_redundancy 0.001 \
  --lambda_contribution 0.05 \
  --lambda_balance 0.01 \
  --contribution_margin 0.0001 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_720 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 512 \
  --d_ff 512 \
  --num_token_heads 4 \
  --use_dynamic_mask 1 \
  --token_mask_hidden 64 \
  --token_temperature 1.0 \
  --gate_temperature 1.0 \
  --fusion_type dynamic \
  --share_prediction_head 0 \
  --lambda_branch 0.2 \
  --lambda_redundancy 0.001 \
  --lambda_contribution 0.05 \
  --lambda_balance 0.01 \
  --contribution_margin 0.0001 \
  --itr 1
